/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as CostRouteImport } from './routes/cost'
import { Route as IndexRouteImport } from './routes/index'

const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/predictions': typeof PredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/predictions': typeof PredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/predictions': typeof PredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cost' | '/models' | '/performance' | '/predictions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cost' | '/models' | '/performance' | '/predictions'
  id: '__root__' | '/' | '/cost' | '/models' | '/performance' | '/predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostRoute: typeof CostRoute
  ModelsRoute: typeof ModelsRoute
  PerformanceRoute: typeof PerformanceRoute
  PredictionsRoute: typeof PredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostRoute: CostRoute,
  ModelsRoute: ModelsRoute,
  PerformanceRoute: PerformanceRoute,
  PredictionsRoute: PredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
